class Card:
    def __init__(
        self,
        artist=None,
        artistIds=None,
        asciiName=None,
        attractionLights=None,
        availability=None,
        boosterTypes=None,
        borderColor=None,
        cardParts=None,
        colorIdentity=None,
        colorIndicator=None,
        colors=None,
        defense=None,
        duelDeck=None,
        edhrecRank=None,
        edhrecSaltiness=None,
        faceConvertedManaCost=None,
        faceFlavorName=None,
        faceManaValue=None,
        faceName=None,
        finishes=None,
        flavorName=None,
        flavorText=None,
        frameEffects=None,
        frameVersion=None,
        hand=None,
        hasAlternativeDeckLimit=None,
        hasContentWarning=None,
        hasFoil=None,
        hasNonFoil=None,
        isAlternative=None,
        isFullArt=None,
        isFunny=None,
        isOnlineOnly=None,
        isOversized=None,
        isPromo=None,
        isRebalanced=None,
        isReprint=None,
        isReserved=None,
        isStarter=None,
        isStorySpotlight=None,
        isTextless=None,
        isTimeshifted=None,
        keywords=None,
        language=None,
        layout=None,
        leadershipSkills=None,
        life=None,
        loyalty=None,
        manaCost=None,
        manaValue=None,
        name=None,
        number=None,
        originalPrintings=None,
        originalReleaseDate=None,
        originalText=None,
        originalType=None,
        otherFaceIds=None,
        power=None,
        printings=None,
        promoTypes=None,
        rarity=None,
        rebalancedPrintings=None,
        relatedCards=None,
        securityStamp=None,
        setCode=None,
        side=None,
        signature=None,
        sourceProducts=None,
        subsets=None,
        subtypes=None,
        supertypes=None,
        text=None,
        toughness=None,
        type=None,
        types=None,
        uuid=None,
        variations=None,
        watermark=None,
    ):
        self.artist = artist
        self.artistIds = artistIds
        self.asciiName = asciiName
        self.attractionLights = attractionLights
        self.availability = availability
        self.boosterTypes = boosterTypes
        self.borderColor = borderColor
        self.cardParts = cardParts
        self.colorIdentity = colorIdentity
        self.colorIndicator = colorIndicator
        self.colors = colors
        self.defense = defense
        self.duelDeck = duelDeck
        self.edhrecRank = edhrecRank
        self.edhrecSaltiness = edhrecSaltiness
        self.faceConvertedManaCost = faceConvertedManaCost
        self.faceFlavorName = faceFlavorName
        self.faceManaValue = faceManaValue
        self.faceName = faceName
        self.finishes = finishes
        self.flavorName = flavorName
        self.flavorText = flavorText
        self.frameEffects = frameEffects
        self.frameVersion = frameVersion
        self.hand = hand
        self.hasAlternativeDeckLimit = hasAlternativeDeckLimit
        self.hasContentWarning = hasContentWarning
        self.hasFoil = hasFoil
        self.hasNonFoil = hasNonFoil
        self.isAlternative = isAlternative
        self.isFullArt = isFullArt
        self.isFunny = isFunny
        self.isOnlineOnly = isOnlineOnly
        self.isOversized = isOversized
        self.isPromo = isPromo
        self.isRebalanced = isRebalanced
        self.isReprint = isReprint
        self.isReserved = isReserved
        self.isStarter = isStarter
        self.isStorySpotlight = isStorySpotlight
        self.isTextless = isTextless
        self.isTimeshifted = isTimeshifted
        self.keywords = keywords
        self.language = language
        self.layout = layout
        self.leadershipSkills = leadershipSkills
        self.life = life
        self.loyalty = loyalty
        self.manaCost = manaCost
        self.manaValue = manaValue
        self.name = name
        self.number = number
        self.originalPrintings = originalPrintings
        self.originalReleaseDate = originalReleaseDate
        self.originalText = originalText
        self.originalType = originalType
        self.otherFaceIds = otherFaceIds
        self.power = power
        self.printings = printings
        self.promoTypes = promoTypes
        self.rarity = rarity
        self.rebalancedPrintings = rebalancedPrintings
        self.relatedCards = relatedCards
        self.securityStamp = securityStamp
        self.setCode = setCode
        self.side = side
        self.signature = signature
        self.sourceProducts = sourceProducts
        self.subsets = subsets
        self.subtypes = subtypes
        self.supertypes = supertypes
        self.text = text
        self.toughness = toughness
        self.type = type
        self.types = types
        self.uuid = uuid
        self.variations = variations
        self.watermark = watermark
